version: 1.0.{build}

environment:
  matrix:
    - compiler: msvc_msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64

before_build:
    - set PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%
    - bash -c "pacman -R catgets libcatgets --noconfirm || true"
    - bash -c "pacman -Syu --noconfirm"
    - bash -c "pacman -Syu --noconfirm"
    - bash -c "pacman -S --noconfirm --needed mingw-w64-%MSYS2_ARCH%-{gcc,gtkmm3,boost,yaml-cpp,sqlite3,toolchain,zeromq,glm,libgit2,oce} zip make"
    - bash -c "pacman -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libgit2-0.27.8-1-any.pkg.tar.xz --noconfirm"

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - echo %cd%
    - dir
    - bash -c "cd $APPVEYOR_BUILD_FOLDER && make -j2 && ./make_bindist.sh"

artifacts:
    - path: dist/horizon-*.zip

test_script:
    - set PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%
    - bash -c "cd $APPVEYOR_BUILD_FOLDER && ./check_dll.sh"
