name: Build Windows binaries

on:
  push:
    branches:
      - '*'
      - '!appveyor-*'
      - '!freebsd-*'
      - '!pr-review'
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build-win32:
    runs-on: windows-latest
    steps:
    - name: Check tag
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "Building tag ${{ github.ref }}"
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-gtkmm3
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-sqlite3
          mingw-w64-x86_64-zeromq
          mingw-w64-x86_64-glm
          mingw-w64-x86_64-libgit2-winhttp
          mingw-w64-x86_64-oce
          mingw-w64-x86_64-podofo
          mingw-w64-x86_64-libzip
          mingw-w64-x86_64-curl-winssl
          mingw-w64-x86_64-jq
          zip
          unzip
          make
          git
          dos2unix
    - name: Downgrade librsvg
      shell: msys2 {0}
      run: pacman -U https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-librsvg-2.50.3-3-any.pkg.tar.zst --noconfirm
    - name: Install patched gtk
      shell: msys2 {0}
      run: |
        curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header "Accept: application/vnd.github.v3+json" -L https://api.github.com/repos/carrotIndustries/gtk3-horizon/actions/artifacts/135986951/zip > artifact.zip
        unzip artifact.zip
        pacman -U --noconfirm mingw-w64-x86_64-gtk*.pkg.tar.zst 
    - name: Build
      shell: msys2 {0}
      run: make -j2 WARNFLAGS="-Wall -Wshadow -Wno-attributes"
    - name: Make dist
      shell: msys2 {0}
      run: ./make_bindist.sh
    - name: Check for missing DLLs
      shell: msys2 {0}
      run: ./check_dll.sh
    - name: set artifact name
      shell: msys2 {0}
      run: echo "artifact_name=horizon-win64-$(date +%Y-%m-%d-%H%M)" >> $GITHUB_ENV
    - name: deploy to artifactory
      if: github.event_name != 'pull_request'
      shell: msys2 {0}
      run: |
        curl -u actions:${{ secrets.ARTIFACTORY }} -T dist/*.zip "https://horizoneda.jfrog.io/artifactory/horizon-win64-ci/$(basename dist/*.zip);commit=${{ github.sha }};ref=${{ github.ref }}" > deploy.json
        echo "::notice title=Download this build::Get the zip archive from Artifactory: $(jq -r .downloadUri < deploy.json)"
    - uses: actions/upload-artifact@v2-preview
      if: github.event_name == 'pull_request'
      with:
        name: ${{ env.artifact_name }}
        path: dist/*.zip
    - name: Build MSI
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/win32-installer'
      run: |
        $env:PATH += ";$($Env:WIX)\bin"
        cd wix
        .\install.bat
    - uses: actions/upload-artifact@v2-preview
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/win32-installer'
      with:
        name: horizon-win64-installer
        path: wix/*.msi
